name: Start debugging
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: shaowenchen/debugger-action@v2
        name: debugger
        timeout-minutes: 90
        continue-on-error: true
        with:
          ngrok_token: ${{ secrets.NGROK_TOKEN }}
